fedimint/fedimint-web-sdk

packages/core-web/package.json
packages/core-web/src/worker.js
packages/core-web/wasm/package.json
pnpm-lock.yaml

* Added Side Effects for tree shaking optimizations
* updated bundled fedimint-client-wasm to private. It shouldn't link to any other package on npm.
* removed wasm folder from the bundled package - since it's already included as `bundledDependencies`

chore: added tree shaking and bundling optimizations

---

.changeset/pink-socks-fetch.md
examples/vite-core/src/App.tsx
packages/core-web/rollup.config.js
packages/core-web/src/FedimintWallet.test.ts
packages/core-web/src/FedimintWallet.ts
packages/core-web/src/services/BalanceService.ts
packages/core-web/src/services/FederationService.ts
packages/core-web/src/services/LightningService.ts
packages/core-web/src/services/MintService.ts
packages/core-web/src/services/RecoveryService.ts
packages/core-web/src/services/index.ts
packages/core-web/src/transport/WorkerClient.ts
packages/core-web/src/transport/index.ts
vitest.config.ts

The FedimintWallet was getting pretty beefy, so this refactor should make the core-web package more manageable & testable. In addition, this structure will make it way easier to organize documentation of the feature set.
* Created Services for each category of functionality:
* Mint Service
* Lightning Service
* Balance Service
* Federation Service
* Recovery Service
* Moved complex web-worker logic to it's own "Worker Client"
* TODO: split up subscription logic into a "subscription" or "rpc" client

Refactor Wallet into multiple Composable services

---

examples/vite-core/vite.config.ts
packages/core-web/src/FedimintWallet.ts
packages/core-web/src/transport/WorkerClient.ts

Can't pass the url into the worker client without breaking Vite's bundling: [ref](https://vitejs.dev/guide/features.html#import-with-constructors)

Fix: Web worker instantiation 

---

.changeset/nervous-beans-chew.md
packages/core-web/src/FedimintWallet.ts
packages/core-web/src/index.ts
packages/core-web/src/worker/WorkerClient.ts
packages/core-web/src/worker/index.ts
packages/core-web/src/worker/types.ts
packages/core-web/src/worker/worker.test.ts

Quickly found it difficult to keep track of the worker messages, and realized the messages will only grow as components like the wallet are built out. This PR introduces `enum WorkerMessageType` for the purposes of tracking and strong typing messages

chore: declare worker message types

---

.changeset/orange-owls-begin.md
packages/core-web/src/services/MintService.ts

This pull request changes the default "expiry" for ecash spends and adjusting the `tryCancelAfter` parameter in the `MintService`.
* [`packages/core-web/src/services/MintService.ts`](diffhunk://#diff-495e82e4c4aee23c5855e8135c9aeffc9955eb42e7ba678e7681f69d63a67ef8L50-R52): Updated the `tryCancelAfter` parameter in the `spendNotes` method to default to 1 day (3600 * 24 seconds).

fix: update default ecash expiry to 1 day

---

.changeset/cool-zoos-rest.md
.changeset/empty-kings-accept.md
.changeset/fifty-papayas-float.md
.changeset/soft-parrots-hear.md
examples/vite-core/package.json
package.json
packages/core-web/src/FedimintWallet.ts
packages/react/lib/contexts/FedimintWalletContext.ts
packages/react/lib/contexts/FedimintWalletContext.tsx
packages/react/lib/contexts/index.ts
packages/react/lib/hooks/index.ts
packages/react/lib/hooks/useBalance.ts
packages/react/lib/hooks/useFedimintWallet.ts
packages/react/lib/hooks/useLightningInvoice.ts
packages/react/lib/hooks/useOpenWallet.ts
packages/react/lib/hooks/useReceiveLightning.ts
packages/react/lib/hooks/useSendLightning.ts
packages/react/lib/index.ts
packages/react/lib/init.ts
packages/react/package.json
packages/react/src/App.css
packages/react/src/App.tsx
packages/react/src/components/HooksDemo.tsx
packages/react/src/index.css
packages/react/src/main.tsx
packages/react/src/types/images.d.ts
packages/react/tsconfig.build.json
packages/react/tsconfig.json
packages/react/vite.config.ts
pnpm-lock.yaml

This pull request introduces a React package. It includes the addition of a new context for the Fedimint Wallet, a custom hook for balance management, and updates to the project configuration files.
* Added `FedimintWalletContext` and `FedimintWalletProvider` to manage the Fedimint Wallet state in the React application (`packages/react/lib/contexts/FedimintWalletContext.tsx`).
* Introduced `useBalance` hook to subscribe to and manage the wallet balance (`packages/react/lib/hooks/useBalance.ts`).
* Introduced `useOpenWallet` hook.
* Introduced `useSendLightning` and `useReceiveLightning` hooks.
* Updated `App.tsx` to use the new `useBalance` hook and display the wallet balance (`packages/react/src/App.tsx`).

feat: Add React Library

---

.github/workflows/verify.yml
flake.nix
package.json
pnpm-lock.yaml

chore: use self-hosted runner for integration tests

---

docs/.vitepress/sidebar.ts
docs/core/FedimintWallet/BalanceService/getBalance.md
docs/core/FedimintWallet/FederationService/getConfig.md
docs/core/FedimintWallet/FederationService/getFederationId.md
docs/core/FedimintWallet/FederationService/getInviteCode.md
docs/core/FedimintWallet/LightningService/createInvoice.md
docs/core/FedimintWallet/LightningService/payInvoice.md
docs/core/FedimintWallet/MintService/parseNotes.md
docs/core/FedimintWallet/MintService/redeemEcash.md
docs/core/FedimintWallet/MintService/spendNotes.md
docs/core/FedimintWallet/initialize.md
packages/core-web/src/services/BalanceService.ts
packages/core-web/src/services/FederationService.ts
packages/core-web/src/services/LightningService.ts
packages/core-web/src/services/MintService.ts
packages/core-web/src/services/RecoveryService.ts
packages/core-web/src/types/utils.ts
packages/core-web/src/types/wallet.ts
packages/core-web/src/worker/WorkerClient.ts

* Added MintService Docs
* Added FederationService Docs
Some light refactors
* Removed unnecessary return types from functions
* Prefer using type parameters over function return types

Clean up Types, Add docs

---

.changeset/orange-rice-rest.md
packages/core-web/src/services/MintService.ts
packages/core-web/src/types/wallet.ts
packages/core-web/src/worker/WorkerClient.ts
packages/react/lib/contexts/FedimintWalletContext.ts
packages/react/lib/hooks/useOpenWallet.ts
packages/react/lib/hooks/useReceiveEcash.ts
packages/react/lib/hooks/useSpendEcash.ts
packages/react/src/App.css
packages/react/src/components/HooksDemo.tsx

* Added missing types to `spendNotes` rpc
* Added error messages to ecash hooks
* Fixed behavior of useOpen hook with concurrent callers

feat: improved error handling on ecash hooks

---

.changeset/big-lies-wonder.md
.changeset/fast-chicken-swim.md
package.json
packages/create-fedimint-app/README.md
packages/create-fedimint-app/package.json
packages/create-fedimint-app/src/index.ts
packages/create-fedimint-app/template-vite-react/README.md
packages/create-fedimint-app/template-vite-react/_gitignore
packages/create-fedimint-app/template-vite-react/index.html
packages/create-fedimint-app/template-vite-react/package.json
packages/create-fedimint-app/template-vite-react/src/App.jsx
packages/create-fedimint-app/template-vite-react/src/index.css
packages/create-fedimint-app/template-vite-react/src/main.jsx
packages/create-fedimint-app/template-vite-react/src/vite-env.d.ts
packages/create-fedimint-app/template-vite-react/src/wallet.ts
packages/create-fedimint-app/template-vite-react/vite.config.ts
pnpm-lock.yaml

Added new template for Vite + React + JS to create-fedimint-app script.

feat: create-script Vite + React + JS template

---

.github/README.md
docs/.vitepress/config.ts
docs/.vitepress/theme/index.ts
docs/core/getting-started.md
docs/package.json
pnpm-lock.yaml

* Updated getting started docs to include create-fedimint-app script instructions.
* Added `vitepress-plugin-group-icons` to get nice icons on files names.

chore: update docs with create-fedimint-app script information

---

examples/vite-core/package.json
pnpm-lock.yaml

The react example wasn't building locally and at https://web.fedimint.org/examples/vite-react.html via StackBlitz

chore: fixes package.json breaking react example

---

flake.lock
flake.nix

Updates  fedimint in dev tools to the newest version 0.6.1
supersedes #116

chore: update fedimint version in devtools to 0.6.1

---

packages/core-web/src/services/MintService.ts

**Context:** While implementing spendNotes its throwing error for not getting amount field in rpc  `RPC response 10 {"error":"missing field amount"}`
Have renamed the min_amount to amount to match the rpc
@alexlwn123 @maan2003

fix: renamed min_amount to amount to match rpc in MintService

---

examples/vite-core/src/App.tsx

This PR adds example implementations of parseInviteCode and parseLightningInvoice to the Vite example.

chore: Add parseInviteCode and parseLightningInvoice to vite example

---

examples/bare-js/package.json
examples/next-js/package.json
examples/vite-core/package.json
examples/webpack-app/package.json

reverts https://github.com/fedimint/fedimint-web-sdk/pull/144
Was causing CI failures due to failing to install deps BEFORE the new versions are published. Will just have to manually bump websdk lib versions in the examples after releases for now.

fix: revert example versioning

---

examples/next-js/package.json
examples/vite-core/package.json
examples/webpack-app/package.json
pnpm-lock.yaml

pinning the version to latest due to changesets breaking on releases. Not super happy about this, but I'm out of ideas.
This is tricky. We need the version bumping to work properly without breaking the stackblitz examples. Typically, we'd use `workspace:*`, but this doesn't work inside of stackblitz.

chore: Pin version in examples to latest

---

.github/workflows/changesets.yml
package.json

Few updated to the changeset workflow
* Re-add verify dependency
* Remove redundant test step
* Remove redundant wasm build

fix: changeset job to avoid rerunning tests

---

.github/workflows/pull-request.yml
flake.lock
flake.nix
scripts/build_wasm.sh

Adds a separate nix input for devimint vs wasm dependencies. This dramatically reduces the time for rebuilds when working with rust/wasm changes, as most of the compilation time comes from devimint.
Also modifies file permissions on the build wasm script to avoid permission issues when rebuilding.

chore: add separate nix input for wasm vs devimint

---

.changeset/moody-doodles-doubt.md
docs/.vitepress/sidebar.ts
docs/core/FedimintWallet/FederationService/getOperation.md
docs/core/FedimintWallet/FederationService/listOperations.md
docs/core/FedimintWallet/FederationService/listTransactions.md
docs/core/FedimintWallet/type-aliases/lastSeenRequest.md
packages/core-web/src/services/FederationService.ts
packages/core-web/src/types/wallet.ts

- Added getOperation method to get Transaction data with the operation id to search for the transaction with specific operationid.
- Added pagination in listOperations method to get transaction history and operations with the paginations.
- Added a listTransactions method to get list of transactions with pagination filtering the listOperations.
Wasm build on [commit#81841444f126d61debca1ca4763db4dcee8b99b2](https://github.com/fedimint/fedimint/commit/81841444f126d61debca1ca4763db4dcee8b99b2)

feat: Added listTransactions, getOperation and enabled pagination in listOperations
