fedimint/fedimint-web-sdk

packages/core-web/package.json, packages/core-web/rollup.config.js, pnpm-lock.yaml
Added [rollup](rollupjs.org) for bundling libraries
=> Bundle packages with Rollup

.changeset/mean-geese-invite.md
=> Bundle packages with Rollup 

.changeset/silent-dancers-matter.md, README.md, examples/vite-core/README.md, examples/vite-core/vite.config.ts, packages/core-web/README.md
* Updated readmes & comments
* Usage guide should be accurate now... this should be sufficient until a proper docs site is set up.
=> Updated READMEs

.changeset/itchy-suits-leave.md, packages/core-web/README.md, packages/core-web/src/FedimintWallet.ts, packages/core-web/src/types/wallet.ts
* Automatically select gateways for lightning payments
* Calls `refresh_gateway_cache` on lightning actions
* fix gateway types
=> fix: gateway selection

packages/core-web/src/FedimintWallet.ts
cc: @maan2003 
* Fixes the unsubscribe behavior for streaming rpcs
* Added comments/descriptions to explain the black magic
=> fix: unsubscribe stream behavior

.github/actions/install-deps/action.yml, .github/workflows/deploy-preview.yml, packages/core-web/rollup.config.js, packages/core-web/src/FedimintWallet.ts, packages/core-web/src/worker.js
=> chore: fix preview workflow

packages/core-web/package.json
* Add local fedimint-client-wasm to bundledDependencies
=> chore: fix bundled dependencies

.changeset/three-students-talk.md, packages/core-web/README.md
* Updated readme with working usage instructions
=> chore: update readme

examples/vite-core/src/App.tsx, examples/vite-core/vite.config.ts, packages/core-web/src/FedimintWallet.ts, packages/core-web/src/worker.js, vitest.workspace.ts
* Fixed open status not being set on load
* Added loading states to forms
* Added constructor docstring
=> fix: example behavior, loading states

examples/vite-core/src/wallet.ts, packages/core-web/src/FedimintWallet.ts, packages/core-web/src/utils/logger.ts, packages/core-web/src/worker/WorkerClient.ts, packages/core-web/src/worker/worker.js
* Add debug logger with multiple level.
* Add `setLoggingLevel` function to wallet client
* Adds some logs throughout
=> feat: add debug logging

examples/bare-js/index.html, examples/bare-js/worker.js
chore: cleanup barejs example code
=> chore: cleanup barejs example code

.changeset/late-glasses-warn.md, examples/nextjs/next-env.d.ts, packages/core-web/src/FedimintWallet.test.ts, packages/core-web/src/FedimintWallet.ts, packages/core-web/src/services/BalanceService.test.ts, packages/core-web/src/services/FederationService.test.ts, packages/core-web/src/services/FederationService.ts, packages/core-web/src/services/LightningService.test.ts, packages/core-web/src/services/LightningService.ts, packages/core-web/src/services/TestingService.ts, packages/core-web/src/worker/WorkerClient.ts
Added tests for:
* FedimintWallet
* BalanceService
* FederationService
* LightningService
Added a new "TestingService" for exposing some internal state (requestCounter, callbackMap). It is only available when testing.
=> feat: added a bunch of tests

docs/.vitepress/config.ts, docs/.vitepress/sidebar.ts, docs/core/overview.md, docs/index.md
fix: base url, links, gradient
=> fix: base url, links, gradient

.github/workflows/verify.yml, docs/core/getting-started.md
=> chore: fix dead link

docs/.vitepress/sidebar.ts, docs/core/FedimintWallet/isOpen.md, docs/core/getting-started.md, docs/examples/bare-js.md, docs/examples/vite-react.md, examples/vite-core/tsconfig.json, examples/vite-core/tsconfig.node.json
* docs: Added open() sidebar item and isOpen() page 
* docs: Added default files to stackblitz previews
* removed unused tsconfig from vite example
=> feat: adjust examples and previews

docs/examples/vite-react.md, examples/bare-js/index.html, packages/core-web/src/services/FederationService.test.ts, packages/core-web/src/services/LightningService.test.ts, packages/core-web/src/test/TestingService.ts, packages/core-web/src/test/setupTests.ts, packages/core-web/src/worker/worker.js, packages/core-web/src/worker/worker.test.ts, vitest.workspace.ts
Trying out copilot generated PR descriptions:
This pull request includes significant changes to the testing setup and documentation for the `core-web` package. The most important changes involve refactoring test cases to use a new `walletTest` fixture, adding new test cases for the worker, and updating documentation with additional resources.
* [`packages/core-web/src/services/FederationService.test.ts`](diffhunk://#diff-9850da9f3993090f04e9d19cba07c6450aecf0f17dcd46a68f3afd346323bde9L1-R6): Refactored test cases to use the new `walletTest` fixture for better setup and teardown management. [[1]](diffhunk://#diff-9850da9f3993090f04e9d19cba07c6450aecf0f17dcd46a68f3afd346323bde9L1-R6) [[2]](diffhunk://#diff-9850da9f3993090f04e9d19cba07c6450aecf0f17dcd46a68f3afd346323bde9L40-R23) …
=> Feat: adds testing fixtures for setup/teardown

.github/workflows/verify.yml, packages/core-web/src/services/LightningService.test.ts
Fixes flakey tests by adding a timeout.
=> fix: added sleep to ln test

packages/core-web/src/services/MintService.ts, packages/core-web/src/types/wallet.ts
Fixes the `spendNotes` function by adding a new `Duration` type.
=> fix: spendNotes args

.changeset/stale-gifts-sip.md, .github/README.md
* Adds fancy header to readme
* Adds packages table
=> feat: Update Repo Readme

packages/core-web/src/services/MintService.ts, packages/core-web/src/types/wallet.ts
* updates spendNotes return type to `{ notes: string, operation_id: string }`
=> fix: update spendNotes return type

packages/core-web/src/services/MintService.ts
* Removes extraneous log from file
=> chore: remove log

docs/.vitepress/config.ts
* Fixes broken twitter preview
* Used [Vitepress's](https://github.com/vuejs/vitepress/blob/main/docs/.vitepress/config/shared.ts) docs site as a reference
=> fix: Twitter Preview

packages/react/package.json
* Update configs to release @fedimint/react
=> Release react package

packages/core-web/src/services/BalanceService.test.ts, packages/core-web/src/services/LightningService.ts, packages/core-web/src/test/fixtures.ts, packages/core-web/src/types/wallet.ts
* Fix new return type for `joinFederation` in tests
=> Fix joinFederation return type in tests

packages/react/README.md, packages/react/src/components/HooksDemo.tsx, packages/react/src/main.tsx
* Add comments and a readme to the @fedimint/react library
=> chore: clean up hooks demo code

.changeset/mighty-eels-thank.md, docs/core/FedimintWallet/cleanup.md, docs/core/FedimintWallet/constructor.md, docs/core/FedimintWallet/isOpen.md, docs/core/FedimintWallet/joinFederation.md, docs/core/FedimintWallet/open.md, docs/core/FedimintWallet/setLogLevel.md, packages/core-web/src/services/BalanceService.ts, packages/core-web/src/services/LightningService.ts, packages/core-web/src/services/MintService.ts, packages/react/src/components/HooksDemo.tsx
* Renamed amount fields to include units (e.g., `amountMsats`) across various services to improve clarity. 
* Added docs pages for the `cleanup`, `isOpen`, `joinFederation`, `open`, and `setLogLevel` methods in the `FedimintWallet` class.
=> Address sdk feedback

.changeset/two-cows-search.md
Adds changeset for https://github.com/fedimint/fedimint-web-sdk/pull/81
=> chore: add changeset

docs/.vitepress/config.ts, docs/.vitepress/sidebar.ts, docs/core/FedimintWallet/index.md, docs/core/dev/awesome.md
* Added an "Awesome Projects" docs page.
* Updated the sidebar to collapse large sections by default.
Enhancements to navigation:
* [`docs/.vitepress/config.ts`](diffhunk://#diff-3def678deb1b1d5a53948eb8491817dde4dc881e032e785fc61cc93d334eefcdR55-R58): Added a new link to the "Awesome Fedimint Web SDK" page in the top navigation bar.
* [`docs/.vitepress/sidebar.ts`](diffhunk://#diff-d77fb9b34398798ea17d74d9ed98610733dda4119bdffc9312fe12f7e06b13ebR7): Updated the sidebar configuration to include new sections and ensure certain sections are not collapsed by default. [[1]](diffhunk://#diff-d77fb9b34398798ea17d74d9ed98610733dda4119bdffc9312fe12f7e06b13ebR7) [[2]](diffhunk://#diff-d77fb9b34398798ea17d74d9ed98610733dda4119bdffc9312fe12f7e06b13ebR18) …
=> feat: add awesome projects docs page

flake.nix
=> chore: add git to nixshell

examples/next-js/package.json, pnpm-lock.yaml
Adds autoprefixer to nextjs example to fix live site demo.
=> fix: nextjs example for stackblitz

docs/.vitepress/sidebar.ts, docs/core/FedimintWallet/LightningService/payInvoice.md, docs/core/FedimintWallet/isOpen.md, docs/core/dev/awesome.md, docs/examples/webpack.md
Adds several minor changes to docs.
* Fixes https://github.com/fedimint/fedimint-web-sdk/issues/139
* Uncollapses sidebar by default
* Added docs page for Webpack example
* Updated the awesome page
=> Minor Docs Fixes

examples/bare-js/package.json, examples/vite-core/package.json, examples/webpack-app/package.json
Standardize examples to use versioning assisted by changesets.
=> chore: Standardize versioning for example projects

.changeset/yummy-parts-swim.md, .prettierignore, flake.lock, flake.nix, package.json, packages/core-web/src/test/TestingService.ts, pnpm-lock.yaml, vitest.workspace.ts
* TESTING IS GREEEN!!!
* bump devimint
Thanks @maan2003
=> fix: bump devimint version and fix tests

packages/react/CHANGELOG.md, packages/react/package.json
lowers version of @fedimint/react from 1.0.0 to 0.1.0
=> chore: fix version

.changeset/thirty-teeth-lick.md
Avoids major bump. Want to keep this under 0.1 for now.
=> chore: update changeset to avoid major bump
